#############################################################################
# Makefile for building: quazip
# Generated by qmake (2.01a) (Qt 4.8.6) on: ?? ?? 30 11:18:43 2015
# Project:  quazip.pro
# Template: subdirs
# Command: c:\Qt\4.8.6\bin\qmake.exe -spec c:\Qt\4.8.6\mkspecs\win32-msvc2010 CONFIG+=declarative_debug -o Makefile quazip.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = c:\Qt\4.8.6\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = move
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
SUBTARGETS    =  \
		sub-quazip \
		sub-qztest

quazip\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) quazip\ $(MKDIR) quazip\ 
	cd quazip\ && $(QMAKE) d:\move\quazip-0.7.1\quazip\quazip.pro -spec c:\Qt\4.8.6\mkspecs\win32-msvc2010 CONFIG+=declarative_debug -o $(MAKEFILE)
sub-quazip-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) quazip\ $(MKDIR) quazip\ 
	cd quazip\ && $(QMAKE) d:\move\quazip-0.7.1\quazip\quazip.pro -spec c:\Qt\4.8.6\mkspecs\win32-msvc2010 CONFIG+=declarative_debug -o $(MAKEFILE)
sub-quazip: quazip\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd quazip\ && $(MAKE) -f $(MAKEFILE)
sub-quazip-make_default: quazip\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd quazip\ && $(MAKE) -f $(MAKEFILE) 
sub-quazip-make_first: quazip\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd quazip\ && $(MAKE) -f $(MAKEFILE) first
sub-quazip-all: quazip\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd quazip\ && $(MAKE) -f $(MAKEFILE) all
sub-quazip-clean: quazip\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd quazip\ && $(MAKE) -f $(MAKEFILE) clean
sub-quazip-distclean: quazip\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd quazip\ && $(MAKE) -f $(MAKEFILE) distclean
sub-quazip-install_subtargets: quazip\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd quazip\ && $(MAKE) -f $(MAKEFILE) install
sub-quazip-uninstall_subtargets: quazip\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd quazip\ && $(MAKE) -f $(MAKEFILE) uninstall
qztest\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) qztest\ $(MKDIR) qztest\ 
	cd qztest\ && $(QMAKE) d:\move\quazip-0.7.1\qztest\qztest.pro -spec c:\Qt\4.8.6\mkspecs\win32-msvc2010 CONFIG+=declarative_debug -o $(MAKEFILE)
sub-qztest-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) qztest\ $(MKDIR) qztest\ 
	cd qztest\ && $(QMAKE) d:\move\quazip-0.7.1\qztest\qztest.pro -spec c:\Qt\4.8.6\mkspecs\win32-msvc2010 CONFIG+=declarative_debug -o $(MAKEFILE)
sub-qztest: qztest\$(MAKEFILE) sub-quazip FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd qztest\ && $(MAKE) -f $(MAKEFILE)
sub-qztest-make_default: qztest\$(MAKEFILE) sub-quazip-make_default FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd qztest\ && $(MAKE) -f $(MAKEFILE) 
sub-qztest-make_first: qztest\$(MAKEFILE) sub-quazip-make_first FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd qztest\ && $(MAKE) -f $(MAKEFILE) first
sub-qztest-all: qztest\$(MAKEFILE) sub-quazip-all FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd qztest\ && $(MAKE) -f $(MAKEFILE) all
sub-qztest-clean: qztest\$(MAKEFILE) sub-quazip-clean FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd qztest\ && $(MAKE) -f $(MAKEFILE) clean
sub-qztest-distclean: qztest\$(MAKEFILE) sub-quazip-distclean FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd qztest\ && $(MAKE) -f $(MAKEFILE) distclean
sub-qztest-install_subtargets: qztest\$(MAKEFILE) sub-quazip-install_subtargets FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd qztest\ && $(MAKE) -f $(MAKEFILE) install
sub-qztest-uninstall_subtargets: qztest\$(MAKEFILE) sub-quazip-uninstall_subtargets FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd qztest\ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: quazip.pro  c:\Qt\4.8.6\mkspecs\win32-msvc2010\qmake.conf c:\Qt\4.8.6\mkspecs\qconfig.pri \
		c:\Qt\4.8.6\mkspecs\modules\qt_webkit_version.pri \
		c:\Qt\4.8.6\mkspecs\features\qt_functions.prf \
		c:\Qt\4.8.6\mkspecs\features\qt_config.prf \
		c:\Qt\4.8.6\mkspecs\features\exclusive_builds.prf \
		c:\Qt\4.8.6\mkspecs\features\default_pre.prf \
		c:\Qt\4.8.6\mkspecs\features\win32\default_pre.prf \
		c:\Qt\4.8.6\mkspecs\features\debug.prf \
		c:\Qt\4.8.6\mkspecs\features\debug_and_release.prf \
		c:\Qt\4.8.6\mkspecs\features\default_post.prf \
		c:\Qt\4.8.6\mkspecs\features\win32\default_post.prf \
		c:\Qt\4.8.6\mkspecs\features\declarative_debug.prf \
		c:\Qt\4.8.6\mkspecs\features\win32\rtti.prf \
		c:\Qt\4.8.6\mkspecs\features\win32\exceptions.prf \
		c:\Qt\4.8.6\mkspecs\features\win32\stl.prf \
		c:\Qt\4.8.6\mkspecs\features\shared.prf \
		c:\Qt\4.8.6\mkspecs\features\win32\embed_manifest_exe.prf \
		c:\Qt\4.8.6\mkspecs\features\win32\embed_manifest_dll.prf \
		c:\Qt\4.8.6\mkspecs\features\warn_on.prf \
		c:\Qt\4.8.6\mkspecs\features\qt.prf \
		c:\Qt\4.8.6\mkspecs\features\win32\thread.prf \
		c:\Qt\4.8.6\mkspecs\features\moc.prf \
		c:\Qt\4.8.6\mkspecs\features\win32\windows.prf \
		c:\Qt\4.8.6\mkspecs\features\resources.prf \
		c:\Qt\4.8.6\mkspecs\features\uic.prf \
		c:\Qt\4.8.6\mkspecs\features\yacc.prf \
		c:\Qt\4.8.6\mkspecs\features\lex.prf \
		c:\Qt\4.8.6\mkspecs\features\include_source_dir.prf
	$(QMAKE) -spec c:\Qt\4.8.6\mkspecs\win32-msvc2010 CONFIG+=declarative_debug -o Makefile quazip.pro
c:\Qt\4.8.6\mkspecs\qconfig.pri:
c:\Qt\4.8.6\mkspecs\modules\qt_webkit_version.pri:
c:\Qt\4.8.6\mkspecs\features\qt_functions.prf:
c:\Qt\4.8.6\mkspecs\features\qt_config.prf:
c:\Qt\4.8.6\mkspecs\features\exclusive_builds.prf:
c:\Qt\4.8.6\mkspecs\features\default_pre.prf:
c:\Qt\4.8.6\mkspecs\features\win32\default_pre.prf:
c:\Qt\4.8.6\mkspecs\features\debug.prf:
c:\Qt\4.8.6\mkspecs\features\debug_and_release.prf:
c:\Qt\4.8.6\mkspecs\features\default_post.prf:
c:\Qt\4.8.6\mkspecs\features\win32\default_post.prf:
c:\Qt\4.8.6\mkspecs\features\declarative_debug.prf:
c:\Qt\4.8.6\mkspecs\features\win32\rtti.prf:
c:\Qt\4.8.6\mkspecs\features\win32\exceptions.prf:
c:\Qt\4.8.6\mkspecs\features\win32\stl.prf:
c:\Qt\4.8.6\mkspecs\features\shared.prf:
c:\Qt\4.8.6\mkspecs\features\win32\embed_manifest_exe.prf:
c:\Qt\4.8.6\mkspecs\features\win32\embed_manifest_dll.prf:
c:\Qt\4.8.6\mkspecs\features\warn_on.prf:
c:\Qt\4.8.6\mkspecs\features\qt.prf:
c:\Qt\4.8.6\mkspecs\features\win32\thread.prf:
c:\Qt\4.8.6\mkspecs\features\moc.prf:
c:\Qt\4.8.6\mkspecs\features\win32\windows.prf:
c:\Qt\4.8.6\mkspecs\features\resources.prf:
c:\Qt\4.8.6\mkspecs\features\uic.prf:
c:\Qt\4.8.6\mkspecs\features\yacc.prf:
c:\Qt\4.8.6\mkspecs\features\lex.prf:
c:\Qt\4.8.6\mkspecs\features\include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -spec c:\Qt\4.8.6\mkspecs\win32-msvc2010 CONFIG+=declarative_debug -o Makefile quazip.pro

qmake_all: sub-quazip-qmake_all sub-qztest-qmake_all FORCE

make_default: sub-quazip-make_default sub-qztest-make_default FORCE
make_first: sub-quazip-make_first sub-qztest-make_first FORCE
all: sub-quazip-all sub-qztest-all FORCE
clean: sub-quazip-clean sub-qztest-clean FORCE
distclean: sub-quazip-distclean sub-qztest-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-quazip-install_subtargets sub-qztest-install_subtargets FORCE
uninstall_subtargets: sub-quazip-uninstall_subtargets sub-qztest-uninstall_subtargets FORCE

sub-quazip-sub_Debug: quazip\$(MAKEFILE)
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd quazip\ && $(MAKE) -f $(MAKEFILE) debug
sub-qztest-sub_Debug: qztest\$(MAKEFILE) sub-quazip-sub_Debug
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd qztest\ && $(MAKE) -f $(MAKEFILE) debug
debug: sub-quazip-sub_Debug sub-qztest-sub_Debug

sub-quazip-sub_Release: quazip\$(MAKEFILE)
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd quazip\ && $(MAKE) -f $(MAKEFILE) release
sub-qztest-sub_Release: qztest\$(MAKEFILE) sub-quazip-sub_Release
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd qztest\ && $(MAKE) -f $(MAKEFILE) release
release: sub-quazip-sub_Release sub-qztest-sub_Release

sub-quazip-check: quazip\$(MAKEFILE)
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd quazip\ && $(MAKE) -f $(MAKEFILE) check
sub-qztest-check: qztest\$(MAKEFILE) sub-quazip-check
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd qztest\ && $(MAKE) -f $(MAKEFILE) check
check: sub-quazip-check sub-qztest-check

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

